version: "3.7"
services:
  frontend:
    image: node:20-alpine3.17
    container_name: frontend
    command: npm run dev
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
